
[[plugins]]
repo = "altercation/vim-colors-solarized"
hook_add = """
colorscheme solarized 
let g:solarized_termcolors=16
let g:solarized_termtrans = 1
set background=dark
let g:airline_theme='solarized'
"""

[[plugins]]
repo = "machakann/vim-sandwich"

[[plugins]]
repo = "cespare/vim-toml"

[[plugins]]
repo = "jparise/vim-graphql"

[[plugins]]
repo = 'junegunn/fzf'
build_on = './install --bin'
merged = '0'
hook_add = '''
set rtp+=/usr/local/opt/fzf
set rtp+=/usr/local/bin/fzf
set rtp+=~/.fzf
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
dependes = 'fzf'
hook_add = '''
command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'source': 'ag --hidden --ignore .git -g ""'}), <bang>0)
command! -bang -nargs=* Ag
  \ call fzf#vim#grep(
  \   'ag --column --color --hidden --ignore .git '.shellescape(<q-args>), 0,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%', '?'),
  \   <bang>0)
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
marged = 0
hook_add = '''
let g:coc_global_extensions = [
      \ 'coc-actions',
      \ 'coc-angular',
      \ 'coc-diagnostic', 
      \ 'coc-eslint', 
      \ 'coc-emmet', 
      \ 'coc-floaterm', 
      \ 'coc-fzf-preview', 
      \ 'coc-git', 
      \ 'coc-html', 
      \ 'coc-htmlhint', 
      \ 'coc-highlight',
      \ 'coc-json', 
      \ 'coc-lists', 
      \ 'coc-lightbulb', 
      \ 'coc-ltex', 
      \ 'coc-markdownlint', 
      \ 'coc-metals', 
      \ 'coc-pairs', 
      \ 'coc-prettier', 
      \ 'coc-python', 
      \ 'coc-snippets', 
      \ 'coc-sourcekit', 
      \ 'coc-stylelintplus', 
      \ 'coc-stylelint', 
      \ 'coc-tailwindcss', 
      \ 'coc-tslint-plugin', 
      \ 'coc-tsserver', 
      \ 'coc-toml', 
      \ 'coc-ultisnips', 
      \ 'coc-yank', 
      \ 'coc-yaml'
\] 
'''

# \ '@yaegassy/coc-volar', 

[[plugins]]
repo = 'cohama/lexima.vim'

# [[plugins]]
# repo = 'preservim/nerdtree'


[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
let g:fern#default_hidden=1
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'thinca/vim-quickrun'
# on = 'QuickRun'
hook_add = '''
	set splitright
	let g:quickrun_config = {}
	let g:quickrun_config._ = {
		\ 'outputter/error/success': 'buffer',
		\ 'outputter/error/error': 'quickfix',
		\ 'outputter/quickfix/open_cmd': 'copen',
		\ 'hook/time/enable': 1,
		\ 'runner': 'vimproc',
		\ 'runner/vimproc/updatetime': 60,
		\ }
	let g:quickrun_config.cpp = {
    \ 'command': 'g++',
    \ 'input': 'stdin.txt',
    \ 'runner': 'system',
    \ 'cmdopt': '-std=c++14 -Wall'
    \ }
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
do = 'make'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
	let g:highlightedyank_highlight_duration = 250
'''

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'brooth/far.vim'

