name: macos

on:
  push:
    branches: [ master ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: set zsh
      run: |
        chmod 755 /usr/local/share/zsh/site-functions
        chmod 755 /usr/local/share/zsh
        chsh -s /bin/zsh

    - name: check $SHELL
      run: echo $SHELL

    - name: whoami
      run: whoami


    - name: chown 
      run: chown -R `whoami` ${GITHUB_WORKSPACE}

    - name: Run install.sh
      run: sh ${GITHUB_WORKSPACE}/install.sh

    - name: relog
      run: exec $SHELL -l

    - name: Run install-envs.sh
      run: sh ${GITHUB_WORKSPACE}/install-envs.sh

